version: "2"

run:
  build-tags:
    - dfrunsecurity
  modules-download-mode: vendor

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - .*\.pb\.go$
      - third_party$
      - builtin$
      - examples$

linters:
  default: none
  enable:
    - depguard
    - revive
    - govet
    - importas
    - ineffassign
    - misspell
    - staticcheck
    - unused
    - bodyclose
    - errname
    - makezero
    - whitespace
    - nolintlint
    - gosec
    - forbidigo

  settings:
    depguard:
      rules:
        main:
          list-mode: lax
          deny:
            # https://go.dev/doc/go1.16#ioutil
            - pkg: "io/ioutil"
              desc: "The io/ioutil package has been deprecated."
    forbidigo:
      forbid:
        - pattern: '^fmt\.Errorf(# use errors\.Errorf instead)?$'
        - pattern: 'logrus\.(Trace|Debug|Info|Warn|Warning|Error|Fatal)(f|ln)?\((# use bklog\.G\(ctx\) instead of logrus directly)?'
    importas:
      alias:
        - pkg: "github.com/opencontainers/image-spec/specs-go/v1"
          alias: "ocispecs"
        - pkg: "github.com/opencontainers/go-digest"
          alias: "digest"
      no-unaliased: true
    gosec:
      excludes:
        - G101  # Potential hardcoded credentials (false positives)
        - G402  # TLS MinVersion too low
        - G601  # Implicit memory aliasing in for loop (false positives)
        - G504  # Import blocklist: net/http/cgi
        - G115  # Many false positives, maybe reconsider after looking closer
        - G306  # Too restrictive; also flags "0o644" permissions
      config:
        G306: "0644"
    staticcheck:
      checks:
        # Defaults
        - all
        - "-ST1000"
        - "-ST1003"
        - "-ST1016"
        - "-ST1020"
        - "-ST1021"
        - "-ST1022"
        # Custom
        - "-QF1008"  # Omit embedded fields from selector expression. (Very noisy)
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - revive
        text: "stutters"
      - linters:
          - revive
        text: "empty-block"
      - linters:
          - revive
        text: "superfluous-else"
      - linters:
          - revive
        text: "unused-parameter"
      - linters:
          - revive
        text: "redefines-builtin-id"
      - linters:
          - revive
        text: "if-return"
      - linters:
          - staticcheck
        text: "SA1019: intoto\\.\\w+ is deprecated"
    paths:
      - ".*\\.pb\\.go$"
      - third_party$
      - builtin$
      - examples$
